--- #YAML:1.0
name:               Net-BlueCoat-SGOS
version:            0.91
abstract:           A module to interact with Blue Coat SGOS-based devices.
author:
    - Matthew Lange <mmlange@cpan.org>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP::Protocol::https:  0
    LWP::UserAgent:       5.8.3.1
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
